# This is a basic workflow to help you get started with Actions

name: CreateBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env: 
      PATH: ".\\"
      BUILD_W32: "CreateBuild.BuildWindows32"
      BUILD_W64: "CreateBuild.BuildWindows64"
      GAME_NAME: "Not The Knees"
      VERSION: "" 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Windows 32 bits
        run: |
            $env:VERSION = "0.$env:GITHUB_RUN_ID"
            Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PATH -executeMethod $env:BUILD_W32 -quit"

      # Runs a set of commands using the runners shell
      - name: Build Windows 64 bits
        run: |
          $env:VERSION = "0.$env:GITHUB_RUN_ID"
          Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PATH -executeMethod $env:BUILD_W64 -quit"
      - uses: actions/upload-artifact@v2
        with:
          name: Ejecutable
          path: Versiones/*
