name: CreateBuild

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    env:
        PATH: ".\\"
        BUILD_WIN32: "CreateBuild.BuildWindows32"
        BUILD_WIN64: "CreateBuild.BuildWindows64"
        GAME_NAME: "NotTheKnees"
        VERSION: 
    steps:
      - uses: actions/checkout@v2
      - name: Build For Windows 32 bits
        run: |
          $env:projectVersion = "0.1.$env:GITHUB_RUN_ID"
          Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PATH -executeMethod $env:BUILD_WIN32 -quit"
      - name: Build For Windows 64 bits
        run: |
          $env:projectVersion = "0.1.$env:GITHUB_RUN_ID"
          Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PATH -executeMethod $env:BUILD_WIN64 -quit"
      - uses: actions/upload-artifact@v2
        with:
          name: ejecutable
          path: Builds/*
